apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: auth-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/shayca12/crypto-platform-gitops.git
    targetRevision: main
    path: charts/auth
    helm:
      valueFiles:
        - ../../envs/dev/auth-values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: crypto-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

